crime_categories = {
    'THEFT': [
        'THEFT OF IDENTITY', 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
        'THEFT PLAIN - PETTY ($950 & UNDER)', 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)',
        'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)', 'THEFT, PERSON',
        'THEFT FROM PERSON - ATTEMPT', 'THEFT PLAIN - ATTEMPT',
        'BIKE - STOLEN', 'BIKE - ATTEMPTED STOLEN', 'PURSE SNATCHING',
        'PURSE SNATCHING - ATTEMPT', 'TILL TAP - PETTY ($950 & UNDER)',
        'THEFT FROM MOTOR VEHICLE - ATTEMPT', 'THEFT, COIN MACHINE - PETTY ($950 & UNDER)',
        'SHOPLIFTING - PETTY THEFT ($950 & UNDER)', 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
        'SHOPLIFTING - ATTEMPT', 'BUNCO, PETTY THEFT', 'BUNCO, GRAND THEFT', 'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
        'EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)', 'DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER',
        'DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01', 'DISHONEST EMPLOYEE - GRAND THEFT',
        'DISHONEST EMPLOYEE - PETTY THEFT', 'PICKPOCKET', 'CREDIT CARDS, FRAUD USE ($950 & UNDER', 'GRAND THEFT / AUTO REPAIR',
        'VEHICLE - STOLEN', 'VEHICLE - ATTEMPT STOLEN', 'VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, BIKES, ETC)'
    ],
    'BURGLARY': [
        'BURGLARY', 'BURGLARY FROM VEHICLE', 'BURGLARY FROM VEHICLE, ATTEMPTED',
        'BURGLARY, ATTEMPTED'
    ],
    'ASSAULT': [
        'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT', 'BATTERY - SIMPLE ASSAULT',
        'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER', 'BATTERY POLICE (SIMPLE)',
        'OTHER ASSAULT', 'BATTERY WITH SEXUAL CONTACT', 'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
        'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT', 'BATTERY ON A FIREFIGHTER',
        'INTIMATE PARTNER - SIMPLE ASSAULT', 'INTIMATE PARTNER - AGGRAVATED ASSAULT'
    ],
    'ROBBERY': [
        'ROBBERY', 'ATTEMPTED ROBBERY'
    ],
    'VANDALISM': [
        'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
        'VANDALISM - MISDEAMEANOR ($399 OR UNDER)'
    ],
    'SEX CRIMES': [
        'RAPE, FORCIBLE', 'RAPE, ATTEMPTED', 'SEXUAL PENETRATION W/FOREIGN OBJECT',
        'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH', 'ORAL COPULATION',
        'LEWD CONDUCT', 'LEWD/LASCIVIOUS ACTS WITH CHILD', 'CHILD PORNOGRAPHY',
        'INDECENT EXPOSURE', 'SEX OFFENDER REGISTRANT OUT OF COMPLIANCE',
        'SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ',
        'HUMAN TRAFFICKING - COMMERCIAL SEX ACTS', 'HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE',
        'PEEPING TOM', 'BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM',
        'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD',
    ],
    'HOMICIDE': [
        'CRIMINAL HOMICIDE', 'MANSLAUGHTER, NEGLIGENT'
    ],
    'VEHICLE CRIMES': [
        'DRIVING WITHOUT OWNER CONSENT (DWOC)',
    ],
    'THREATS': [
        'CRIMINAL THREATS - NO WEAPON DISPLAYED', 'BRANDISH WEAPON', 'STALKING',
        'THREATENING PHONE CALLS/LETTERS'
    ],
    'FRAUD/FORGERY': [
        'DOCUMENT FORGERY / STOLEN FELONY', 'COUNTERFEIT', 'CREDIT CARDS, FRAUD USE ($950 & UNDER)',
        'CREDIT CARDS, FRAUD USE ($950.01 & OVER)', 'UNAUTHORIZED COMPUTER ACCESS',
        'DOCUMENT WORTHLESS ($200.01 & OVER)', 'DOCUMENT WORTHLESS ($200 & UNDER)'
    ],
    'COURT/LEGAL VIOLATIONS': [
        'VIOLATION OF COURT ORDER', 'VIOLATION OF RESTRAINING ORDER', 'CONTEMPT OF COURT',
        'VIOLATION OF TEMPORARY RESTRAINING ORDER',
    ],
    'CHILDREN': [
        'KIDNAPPING', 'CHILD NEGLECT (SEE 300 W.I.C.)', 'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)',
        'KIDNAPPING - GRAND ATTEMPT', 'CHILD STEALING', 'CHILD ANNOYING (17YRS & UNDER)', 'DRUGS, TO A MINOR', 'CHILD ABANDONMENT',
    ],
    'WEAPONS': [
        'DISCHARGE FIREARMS/SHOTS FIRED', 'FIREARMS EMERGENCY PROTECTIVE ORDER',
        'FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO)', 'REPLICA FIREARMS(SALE,DISPLAY)',
        'REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)', 'BOMB SCARE', 'WEAPONS POSSESSION/BOMBING'
    ],
    'OTHER': [
        'TRESPASSING', 'ARSON',  'DISTURBING THE PEACE',
        'RESISTING ARREST', 'FALSE IMPRISONMENT', 'PROWLER', 'EXTORTION', 'RECKLESS DRIVING', 'ILLEGAL DUMPING',
        'CONSPIRACY', 'BRIBERY', 'BIGAMY', 'PANDERING', 'BLOCKING DOOR INDUCTION CENTER',
        'FAILURE TO YIELD', 'LYNCHING', 'PIMPING',
        'DISRUPT SCHOOL', 'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT',
        'SHOTS FIRED AT INHABITED DWELLING', 'THROWING OBJECT AT MOVING VEHICLE',
        'OTHER MISCELLANEOUS CRIME', 'CRUELTY TO ANIMALS', 'FALSE POLICE REPORT',
        'CONTRIBUTING', 'DRUNK ROLL', 'TELEPHONE PROPERTY - DAMAGE', 'BUNCO, ATTEMPT'
    ],
}